### ISSUE TITLE
Implementation unfreezing request and unfreezing operation

### ISSUE THREAD

**Issue by soonkuk** [bosnet/sebak#360] opened 2018-09-11 02:09 UTC
## Background
When a client generates a unfreezing transaction, it really affects the balance of account after X blocks.
This is the unfreezing feature.

## Solution
To implement unfreezing features, two operation type is needed.
One is unfreezing request operation, and the other is unfreezing operation.

1. Client who want to unfreeze the frozen account send unfreezing request transaction.
    This transaction doesn't change the balance of the frozen account.
2. After X blocks, client who already sent unfreezing request transaction send again unfreezing transaction.
    This transaction affect the balance of the frozen account. a whole amount of balance is withdrawn from     
    frozen account.

**Comment by Geod24** [comment] 2018-09-11 02:11
Isn't this a duplicate of https://github.com/bosnet/sebak/issues/309 ?

**Comment by kfangw** [comment] 2018-09-14 06:00
> I understood at first we implement unfreezing request and unfreezing transaction type and #309 is implemented after more time.
> So I think this is different issue with #309.

I also confused. I think that it is duplicated.
What #309 intended is to implement the `operation`.

**Closed** 2018-10-17 04:19 UTC
Labels: frozen
