### ISSUE TITLE
'Checkpoint' must not be made formerly, client can not guess the checkpoint of it’s transaction

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#35] opened 2018-06-02 05:21 UTC

**Comment by Geod24** [comment] 2018-06-20 04:59
Can you provide more details ? Or is this a duplicate of https://github.com/bosnet/sebak/issues/60 ?

**Comment by Geod24** [comment] 2018-06-29 07:21
I assume it was. Also, we have #123 now.

**Comment by spikeekips** [comment] 2018-06-29 07:54
#123 is just proposal at this time. This issue still is valid for this code.

**Comment by Geod24** [comment] 2018-06-29 07:58
So can you provide more details on what you mean by "not made formally" ?

**Comment by spikeekips** [comment] 2018-06-29 08:05
@Geod24 I mean, before sending transaction, client must get the latest checkpoint of it's account. Under the current checkpoint mechanism, the next checkpoint can be calculated.

**Closed** 2018-09-18 02:48 UTC
Labels: enhancement
